[project]
name = "reimagined"
version = "0.1.0"
authors = [{name = "Patrick Herring", email="pkherring@gmail.com"}]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.mypy]
plugins = ["pydantic.mypy"]

[tool.coverage.paths]
source = ["src"]

